### PR TITLE
[9] - User with given id does not exist

### LINKED ISSUE #9: As Client I want to get User data
**Description**

**Example**

Happy path:
Request: GET  /api/user/1

Response:  200 OK
```
{
 id: 1
 email: test@user.com
}
```

Userid does not exits

Request: GET  /api/user/999

Response: 400 Bad Response
```
{
 error: 'user does not exist
}
```

### PR DESCRIPTION
**Pull request by LeWricka**
**Resolves**
Resolve #9

### CODE REVIEW

File: src/routes/api.php [hunk 1]
```diff
@@ -25,3 +26,5 @@
 );
 
 Route::get('user/{email}', IsEarlyAdopterUserController::class);
+
```
Comment (LeWricka) [inline src/routes/api.php]: This space is not necessary, remove please

Comment (LeWricka) [reply src/routes/api.php]: Done!

**Review by LeWricka — COMMENTED** [review]
Ok to merge
